basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_remove/', views.basket_remove, name='basket_remove'),
]

game_ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gaming_shop.urls', namespace='shop')),
    path("admin/", admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gaming_shop/urls.py
from argparse import Namespace
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('games/<slug:slug>', views.product_item, name='product_item'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

login/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.login, name='login'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_up/<slug:uidb64>/<slug:token>)/', views.authenticate, name='authenticate')
]

gaming_shop/models.py
from email.policy import default
from django.db import models
from django.urls import reverse
from game_ecommerce_site.settings import AUTH_USER_MODEL

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("shop:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class Platform(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default="images/default.jpg")
    developer = models.CharField(max_length=255)
    publisher = models.CharField(max_length=255)
    # TODO: change so that there can be numerous platforms for a single product
    platforms = models.ManyToManyField(Platform, blank=True, related_name="product")
    release_date = models.DateField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("shop:product_item", args=[self.slug])
    
    def __str__(self):
        return self.title

gaming_shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product, Platform



def index(request):
    products = Product.products.all()
    return render(request, 'gaming_shop/index.html', {'products': products})

def product_item(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'gaming_shop/products/game_item.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'gaming_shop/products/category.html', {'category': category, 'products': products})

templates/gaming_shop/products/category.html
{% extends "../base.html" %} 
{% load static %} 
{% block title %} Home {% endblock title %} 

{% block content %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="pb-3 h5 bg-light">{{ category.name|title }}</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for p in products %}
      <div class="col">
        <div class="card shadow-sm">
          <img class="img-fluid" width="100%" height="225" src="{{ p.image.url }}" alt="{{ p.title }}">
            <title>{{ p.title|title }}</title>
            <rect width="100%" height="100%" fill="#55595c" />
          </svg>
          
          <div class="card-body">
            <div class="card-title"><a href="{{ p.get_absolute_url }}">{{ p.title|title }}</a></div>
            <p class="card-text">
                {{ p.description|truncatewords:25 }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  View
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  Buy
                </button>
              </div>
              <small class="text-muted">Released: {{ p.release_date }}</small>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

templates/gaming_shop/products/game_item.html
{% extends "../base.html" %}

{% block content %}
<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first">
                <img class="img-fluid mx-auto d-block" width="auto" height="auto" alt="{{ product.title|title }}" src="{{ product.image.url }}" alt="">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.developer }}</span></p>
                <p>{{ product.description }}</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">CD</div>
                            <div class="col-6 text-end">
                                <span class="h4 fw-bold">£{{ product.price }}</span>
                            </div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Platform</label>
                                <select id="select">
                                    {% for platform in product.platforms.all %}
                                    <option value="">{{ platform }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col-6 text-end">
                                <button type="button" class="btn btn-dark" id="add-button" value="{{ product.id }}">
                                    Add to basket
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>

<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: 1,
                platform: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'POST',
            },
            success: function (json){
                document.getElementById("basket-quantity").innerHTML = json.quantity

            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock content %}