basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_remove/', views.basket_remove, name='basket_remove'),
]

game_ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gaming_shop.urls', namespace='shop')),
    path("admin/", admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gaming_shop/urls.py
from argparse import Namespace
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('games/<slug:slug>', views.product_item, name='product_item'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

login/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.login, name='login'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_up/<slug:uidb64>/<slug:token>)/', views.authenticate, name='authenticate')
]

gaming_shop/models.py
from email.policy import default
from django.db import models
from django.urls import reverse
from game_ecommerce_site.settings import AUTH_USER_MODEL

class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse("shop:category_list", args=[self.slug])

    def __str__(self):
        return self.name


class Platform(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default="images/default.jpg")
    developer = models.CharField(max_length=255)
    publisher = models.CharField(max_length=255)
    # TODO: change so that there can be numerous platforms for a single product
    platforms = models.ManyToManyField(Platform, blank=True, related_name="product")
    release_date = models.DateField(blank=True)
    slug = models.SlugField(max_length=255, unique=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse("shop:product_item", args=[self.slug])
    
    def __str__(self):
        return self.title

login/models.py
from django.db import models
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager, PermissionsMixin)
from django_countries.fields import CountryField
from django.utils.translation import gettext_lazy as _
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.mail import send_mail
import os

class CustomAccountManager(BaseUserManager):
    def create_superuser(self, email, username, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True.')
        if other_fields.get('is_superuser') is not True:
            raise ValueError(
                'Superuser must be assigned to is_superuser = True'
            )
        return self.create_user(email, username, password, **other_fields)

    def create_user(self, email, username, password, **other_fields):
        if not email:
            raise ValueError(_('You must provide an email address.'))
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **other_fields)
        user.set_password(password)
        user.save()
        return user


class UserBase(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(max_length=150, blank=True)
    last_name = models.CharField(max_length=150, blank=True)
    country = CountryField()
    date_of_birth = models.DateField(max_length=8)
    phone_number = PhoneNumberField(null=False, blank=False, unique=True)
    town_city = models.CharField(max_length=150, blank=True)
    is_active = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now=True)
    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name',
                        'last_name', 'country', 'phone_number', 
                        'date_of_birth', 'town_city',]


    class Meta:
        verbose_name = "Accounts"
        verbose_name_plural = "Accounts"

    def __str__(self):
        return self.email

    def email_user(self, subject, message, registrant):
        send_mail(
            subject=subject,
            message=message,
            recipient_list=[str(registrant), ],
            from_email=os.getenv('EMAIL_ADDRESS'),
            auth_user=os.getenv('EMAIL_ADDRESS'),
            auth_password=os.getenv('EMAIL_PASSWORD'),
            fail_silently=False,
        )

login/forms.py
from django import forms
from .models import UserBase
from django_countries import widgets, countries
from phonenumber_field.formfields import PhoneNumberField
from django.forms.widgets import DateInput
from phonenumber_field.widgets import PhoneNumberPrefixWidget
from datetime import date
from dateutil.relativedelta import relativedelta



class RegistrationForm(forms.ModelForm):
    email = forms.CharField(
        label='Enter Email', min_length=5, max_length=100, help_text='Required', 
        error_messages={'required': 'Please enter a valid email address.'}
    )
    first_name = forms.CharField(
        label="First Name", min_length=1,
        max_length=25,
        required=True,
        error_messages={'required': 'Please enter your first name.'}
    )
    last_name = forms.CharField(
        label="Last Name", min_length=1,
        max_length=25, help_text='Required',
        error_messages={'required': 'Please enter a valid password.'}
    )
    password = forms.CharField(
        label='Password', widget=forms.PasswordInput,
        error_messages={'required': 'Please enter a matching password.'}
        )
    password2 = forms.CharField(
        label='Repeat Password', widget=forms.PasswordInput,
        error_messages={'required': 'Please enter a matching password.'}
        )
        # TODO: Need to fix years available
    date_of_birth = forms.DateField(
        label="Date of Birth", widget=forms.SelectDateWidget(
            years=[x for x in range(date.today().year-100, date.today().year-8)]
        ),
        error_messages={'required': 'Please enter a matching password.'}
    )
    country = forms.ChoiceField(label='Country of Residence', 
        widget=widgets.CountrySelectWidget, choices=countries,
        error_messages={'required': 'Please choose your country.'}
        )
        # TODO: need to finish phone number widget validation
        # https://django-phonenumber-field.readthedocs.io/en/latest/reference.html#widgets

    town_city = forms.CharField(
        label="town/city", min_length=2,
        max_length=40
    )    
    phone_number = PhoneNumberField(
        label="Phone Number",
        widget=PhoneNumberPrefixWidget(   
            )
        )
    phone_number.error_messages['invalid'] = 'Invalid Mobile Number'
    town_city = forms.CharField(label="City", min_length=2, max_length=100, help_text='Required')
    terms = forms.BooleanField(
        label="I have read and agree to the terms and conditions.",
        error_messages={'required': 'Agreeing to terms and conditions is required for account creation.'})

    class Meta:
        model = UserBase
        fields = '__all__'

        widgets = {
            'date_of_birth': DateInput()
        }

    def clean_email(self):
        email = self.cleaned_data['email']
        r = UserBase.objects.filter(email=email)
        if r.count():
            raise forms.ValidationError("Username already exists")
        return email

    def password2_check(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match.')
        return cd['password2']

    

    # TODO: Finish adding validations for form fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs.update(
            {'class': 'form-control mb-3'}
        )
        self.fields['first_name'].widget.attrs.update(
            {'class': 'form-control mb-3'}
        )
        self.fields['last_name'].widget.attrs.update(
            {'class': 'form-control mb-3'}
        )
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control mb-3'}
        )
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control mb-3'}
        )
        #TODO: Finish adding attributes to widgets
        #TODO: Need to add CSS styling that works with bootstrap for the forms


class LoginForm(forms.ModelForm):
    pass
    

gaming_shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Category, Product, Platform



def index(request):
    products = Product.products.all()
    return render(request, 'gaming_shop/index.html', {'products': products})

def product_item(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'gaming_shop/products/game_item.html', {'product': product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.objects.filter(category=category)
    return render(request, 'gaming_shop/products/category.html', {'category': category, 'products': products})

login/views.py
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from phonenumber_field.phonenumber import PhoneNumber
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes, force_str
from .token_generator import account_activation_token
from django.http import HttpResponse


def login(request):
    return render(request, 'login/login.html')

def sign_up(request):
    #TODO add google sign_up/login


    # if request.user.is_authenticated:
    #     return redirect('/')
        #TODO: redirect to user dashboard after creations instead of home page
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)
        if registration_form.is_valid():
            user = registration_form.save(commit=False)
            user.email = registration_form.cleaned_data['email']
            user.first_name = registration_form.cleaned_data['first_name']
            user.last_name = registration_form.cleaned_data['last_name']
            user.set_password(registration_form.cleaned_data['password'])
            user.country = registration_form.cleaned_data['country']
            user.date_of_birth = registration_form.cleaned_data['date_of_birth']
            user.phone_number = registration_form.cleaned_data['phone_number']
            user.town_city = registration_form.cleaned_data['town_city']
            user.is_active = False
            user.save()
            # Set up email
            #TODO: need to set up send email
            #TODO: need to add phone number validation
            #TODO: need to add password strength checker

            current_site = get_current_site(request)
            subject = 'Activate your Account'  
            message = render_to_string(
                'login/registration/account-activation-email.html',
                {
                'user': user,
                'domain': current_site.domain,
                'uidb64': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                })
            user.email_user(subject=subject, message=message, registrant=user)
            render(request, 'login/registration/authenticate-message.html')
        else:
            print(registration_form.errors.as_data())
        return render(request, 'login/registration/sign-up.html', {'form': registration_form})

    else:
        registration_form = RegistrationForm()
        return render(request, 'login/registration/sign-up.html', {'form': registration_form})

def authenticate(request):
    return render(request, 'login/registration/authenticate-message.html')

templates/gaming_shop/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <title>{% block title %}My Shop{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
        <!-- Font Awesome -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        rel="stylesheet"
        />
        <!-- Google Fonts -->
        <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
        />
        <!-- MDB -->
        <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css"
        rel="stylesheet"
        />
        <script src="https://code.jquery.com/jquery-3.6.1.min.js" integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/8866b100a0.js" crossorigin="anonymous"></script>
        <!-- CSS -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <img src="{% static 'gs.png' %}" width="50" height="50" alt="">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Categories
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                        {% for c in categories %}
                        <li>
                            <a class="dropdown-item" href="{{ c.get_absolute_url }}">{{ c.name|title }}</a>
                        </li>
                        {% endfor %}
                        
                    </ul>
                    </li>
                    
                </ul>
                <button type="button" class="btn btn-dark"><a href="{% url 'login:login' %}">Log In</a></button>
                <button type="button" class="btn btn-dark"><a href="{% url 'login:sign_up' %}">Sign Up</a></button>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-dark" type="submit">Search</button>
                </form>
                </div>
                <a href="{% url 'basket:basket_summary' %}" type="button" role="button" class="btn btn-dark">
                    {% with total_quantity=basket|length %}
                    <div id="basket-quantity" class="d-inline-flex">
                        {% if total_quantity > 0 %}
                            {{ total_quantity }}
                        {% else %}
                            0
                        {% endif %}
                    </div>
                    {% endwith %}
                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-cart2" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                    </svg>
                </a> 

            </div>
            </nav>
        </header>

        
        <div id="content">{% block content %} {% endblock content %}</div>
        

        {% block js %}
        {% endblock %}
    </body>
</html>

templates/gaming_shop/index.html
{% extends "./base.html" %} 
{% load static %} 
{% block title %} Home {% endblock title %} 

{% block content %}
{% comment %} carousel displaying most popular games {% endcomment %}
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner" style="height: 410px">
    {% comment %} need to make carousel show 3 products according to some criteria {% endcomment %}
    {% with products|first as first_product %}
    <div class="carousel-item active" data-bs-interval="10000">
      <div class="d-flex justify-content-center">
        <img src="{{ first_product.image.url }}" class="d-block mh-100 mw-100 img-fluid" alt="...">
      </div>
      <div class="carousel-caption d-md-block">
        <h5>{{ first_product.title }}</h5>
        <p>{{ first_product.description|truncatewords:25 }}</p>
      </div>
    </div>
    {% endwith %}
    <div class="carousel-item" data-bs-interval="2000">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div> 




{% comment %} games listing area {% endcomment %}
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    {% for p in products %}
      <div class="col">
        <div class="card shadow-sm">
          <img class="img-fluid" width="100%" height="225" src="{{ p.image.url }}" alt="{{ p.title }}">
            <title>{{ p.title|title }}</title>
            <rect width="100%" height="100%" fill="#55595c" />
          

          <div class="card-body">
            <div class="card-title"><a href="{{ p.get_absolute_url }}">{{ p.title|title }}</a></div>
            <p class="card-text">
                {{ p.description|truncatewords:25 }}
            </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  View
                </button>
                <button type="button" class="btn btn-sm btn-outline-secondary">
                  Buy
                </button>
              </div>
              <small class="text-muted">Released: {{ p.release_date }}</small>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

templates/gaming_shop/login.html
{% extends "./base.html" %}
{% load static %}
{% block title %}
    Login
{% endblock title %}
{% block content %}
    <section class="h-100 h-custom" style="background-color: #eee;">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col">
                    <div class="card">
                        <div class="card-body p-4">
                            <div class="row">
                                <div>
                                    <form>
                                        <div class="text-center mb-3">
                                            <p>Sign in with:</p>
                                            <button type="button" class="btn btn-link btn-floating mx-1">
                                                <i class="fab fa-facebook-f"></i>
                                            </button>
                                            <button type="button" class="btn btn-link btn-floating mx-1">
                                                <i class="fab fa-google"></i>
                                            </button>
                                            <button type="button" class="btn btn-link btn-floating mx-1">
                                                <i class="fab fa-twitter"></i>
                                            </button>
                                            <button type="button" class="btn btn-link btn-floating mx-1">
                                                <i class="fab fa-github"></i>
                                            </button>
                                        </div>
                                        <p class="text-center">or:</p>
                                        <!-- Email input -->
                                        <div class="col-md-4 offset-md-4">
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="loginName">Email or username</label>
                                                <input type="email" id="loginName" class="form-control" />
                                            </div>
                                        </div>
                                        <!-- Password input -->
                                        <div class="col-md-4 offset-md-4">
                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="loginPassword">Password</label>
                                                <input type="password" id="loginPassword" class="form-control" />
                                            </div>
                                        </div>
                                        <!-- 2 column grid layout -->
                                        <div class="row mb-4">
                                            <div class="col-md-6 d-flex justify-content-center">
                                                <!-- Checkbox -->
                                                <div class="form-check mb-3 mb-md-0">
                                                    <input class="form-check-input"
                                                            type="checkbox"
                                                            value=""
                                                            id="loginCheck"
                                                            checked/>
                                                    <label class="form-check-label" for="loginCheck">Remember me</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6 d-flex justify-content-center">
                                                <!-- Simple link -->
                                                <a href="#!">Forgot password?</a>
                                            </div>
                                        </div>
                                        <!-- Submit button -->
                                        <div class="row-mb-4">
                                            <div class="col-md-12 d-flex justify-content-center">
                                                <button type="submit" class="btn btn-primary mb-4">Sign in</button>
                                            </div>
                                        </div>
                                        <!-- Register buttons -->
                                        <div class="text-center">
                                            <p>
                                                Not a member? <a href="{% url 'login:sign_up' %}">Register</a>
                                            </p>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}