basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('basket_add/', views.basket_add, name='basket_add'),
    path('basket_remove/', views.basket_remove, name='basket_remove'),
]

game_ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('gaming_shop.urls', namespace='shop')),
    path("admin/", admin.site.urls),
    path('basket/', include('basket.urls', namespace='basket')),
    path('login/', include('login.urls', namespace='login')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from . import views

app_name = "login"

urlpatterns = [
    path('', views.login, name='login'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_up/<slug:uidb64>/<slug:token>)/', views.authenticate, name='authenticate')
]

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .basket import Basket
from gaming_shop.models import Product


def basket_summary(request):

    return render(request, 'basket/summary.html')

def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'POST':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        platform = str(request.POST.get('platform'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, quantity=product_qty, platform=platform)
        basket_qty = basket.__len__()
        response = JsonResponse({'quantity': basket_qty})
        return response

def basket_remove(request):
    basket = Basket(request)
    if request.POST.get('action') == 'POST':
        product_id = str(request.POST.get('productid'))
        print(product_id)
        basket.remove(product_id=product_id)
        basket_qty = basket.__len__()
        basket_price = basket.get_total_price()
        response = JsonResponse({'quantity': basket_qty, 'totalprice': basket_price, 'productid': product_id})
        return response

templates/basket/summary.html
{% extends '../gaming_shop/base.html' %}
{% load static %}
{% block title %}Basket Summary{% endblock title %}

{% block content %}
{% comment %} need to check basket contains values  {% endcomment %}

<section class="h-100 h-custom" style="background-color: #eee;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col">
          <div class="card">
            <div class="card-body p-4">
  
              <div class="row">
  
                <div class="col-lg-7">
                  <h5 class="mb-3"><a href="#!" class="text-body"><i
                        class="fas fa-long-arrow-alt-left me-2"></i>Continue shopping</a></h5>
                  <hr>
  
                  <div class="d-flex justify-content-between align-items-center mb-4">
                    <div>
                      <p class="mb-1">Shopping cart</p>
                      <p class="mb-0">You have
                        <span id="cart-total">
                          {% with total_quantity=basket|length %}
                            {% if total_quantity > 0 %}
                                {{ total_quantity }} 
                            {% else %}
                                0
                            {% endif %}
                          {% endwith %}
                        </span>
                      items in your cart</p>
                    </div>
                    <div>
                      <p class="mb-0"><span class="text-muted">Sort by:</span> <a href="#!"
                          class="text-body">Price <i class="fas fa-angle-down mt-1"></i></a></p>
                    </div>
                  </div>
  
                  {% for key, value in basket.basket.items %}
                  <div class="card mb-3 mb-lg-0 card{{ key }}">
                    <div class="card-body">
                      <div class="d-flex justify-content-between">
                        <div class="d-flex flex-row align-items-center">
                          <div>
                            <img
                              src="{{ value.image_url }}"
                              class="img-fluid rounded-3" alt="Shopping item" style="width: 65px;">
                          </div>
                          <div class="ms-3">
                            <h5>{{ value.title }}</h5>
                            <p class="small mb-0">{{ value.platform }}</p>
                          </div>
                        </div>
                        <div class="d-flex flex-row align-items-center">
                          <div style="width: 100px;">
                            <p class="mb-0">
                                <button type="button" class="btn btn-dark" id="remove-button" value="{{ key }}">
                                Remove
                                </button>
                            </p>
                          </div>
                          <div style="width: 80px;">
                            <h5 class="mb-0">£{{ value.price }}</h5>
                          </div>
                          <a href="#!" style="color: #cecece;"><i class="fas fa-trash-alt"></i></a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}

  
                </div>
                <div class="col-lg-5">
  
                  <div class="card bg-primary text-white rounded-3">
                    <div class="card-body">
                      <div class="d-flex justify-content-between align-items-center mb-4">
                        <h5 class="mb-0">Card details</h5>
                        <img src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/avatar-6.webp"
                          class="img-fluid rounded-3" style="width: 45px;" alt="Avatar">
                      </div>
  
                      <p class="small mb-2">Card type</p>
                      <a href="#!" type="submit" class="text-white"><i
                          class="fab fa-cc-mastercard fa-2x me-2"></i></a>
                      <a href="#!" type="submit" class="text-white"><i
                          class="fab fa-cc-visa fa-2x me-2"></i></a>
                      <a href="#!" type="submit" class="text-white"><i
                          class="fab fa-cc-amex fa-2x me-2"></i></a>
                      <a href="#!" type="submit" class="text-white"><i class="fab fa-cc-paypal fa-2x"></i></a>
  
                      <form class="mt-4">
                        <div class="form-outline form-white mb-4">
                          <input type="text" id="typeName" class="form-control form-control-lg" siez="17"
                            placeholder="Cardholder's Name" />
                          <label class="form-label" for="typeName">Cardholder's Name</label>
                        </div>
  
                        <div class="form-outline form-white mb-4">
                          <input type="text" id="typeText" class="form-control form-control-lg" siez="17"
                            placeholder="1234 5678 9012 3457" minlength="19" maxlength="19" />
                          <label class="form-label" for="typeText">Card Number</label>
                        </div>
  
                        <div class="row mb-4">
                          <div class="col-md-6">
                            <div class="form-outline form-white">
                              <input type="text" id="typeExp" class="form-control form-control-lg"
                                placeholder="MM/YYYY" size="7" id="exp" minlength="7" maxlength="7" />
                              <label class="form-label" for="typeExp">Expiration</label>
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-outline form-white">
                              <input type="password" id="typeText" class="form-control form-control-lg"
                                placeholder="&#9679;&#9679;&#9679;" size="1" minlength="3" maxlength="3" />
                              <label class="form-label" for="typeText">CVV</label>
                            </div>
                          </div>
                        </div>
  
                      </form>
  
                      <hr class="my-4">
  
                      <div class="d-flex justify-content-between">
                        <p class="mb-2">Subtotal</p>
                        {% if basket|length > 0 %}
                        <p class="mb-2">£{{ basket.get_total_price }}</p>
                        {% else %}
                        <p class="mb-2">£0.00</p>
                        {% endif %}

                      </div>
  
                      <div class="d-flex justify-content-between mb-4">
                        <p class="mb-2">Total (Incl. VAT)</p>
                        {% if basket|length > 0 %}
                        <p class="mb-2">£{{ basket.get_total_price }}</p>
                        {% else %}
                        <p class="mb-2">£0.00</p>
                        {% endif %}

                      </div>
  
                      <button type="button" class="btn btn-info btn-block btn-lg">
                        <div class="d-flex justify-content-between">
                          <span>$4818.00</span>
                          <span>Checkout <i class="fas fa-long-arrow-alt-right ms-2"></i></span>
                        </div>
                      </button>
  
                    </div>
                  </div>
  
                </div>
  
              </div>
  
            </div>
          </div>
        </div>
      </div>
    </div>
</section>


{% comment %} TODO: Need to update basket quantity and price upon basket item removal {% endcomment %}
<script>
    $(document).on('click', '#remove-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_remove" %}',
            data: {
                productid: $('#remove-button').val(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'POST',
            },
            success: function (json){
                $('div').remove('.card'+json.productid)
                document.getElementById("basket-quantity").innerHTML = json.quantity
                document.getElementById("cart-total").innerHTML = json.quantity
            },
            
            error: function (xhr, errmsg, err) {

            },
        });
    })
</script>


{% endblock %}